version: '3'

services:

  controller:
    image: 'trinodb/trino'
    hostname: trino
    volumes:
      - ./etc/catalog:/etc/trino/catalog
    ports:
      - '8080:8080'
    depends_on:
      object-store:
        condition: service_healthy

  object-store:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
    healthcheck:
      test: ["CMD-SHELL", "mc alias set minio http://localhost:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} && mc mb minio/warehouse && mc anonymous set public minio/warehouse"]
      interval: 2s
      timeout: 2s
      retries: 5